name: Build & Release

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.rid }} | self-contained=${{ matrix.self }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # ================= Windows =================
          - os: windows-latest
            rid: win-x86
            exe: true
          - os: windows-latest
            rid: win-x64
            exe: true
          - os: windows-latest
            rid: win-arm
            exe: true
          - os: windows-latest
            rid: win-arm64
            exe: true

        self:
          - true
          - false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish
        shell: bash
        run: |
          if [ "${{ matrix.self }}" = "true" ]; then
            SC_SUFFIX="-selfcontained"
          else
            SC_SUFFIX="-framework"
          fi

          OUTDIR="publish"
          dotnet publish yt-dlp-gui.csproj \
            -c Release \
            -r ${{ matrix.rid }} \
            --self-contained ${{ matrix.self }} \
            /p:PublishSingleFile=true \
            /p:PublishTrimmed=false \
            -o "$OUTDIR"

          cd "$OUTDIR"

          if [ "${{ matrix.exe }}" = "true" ]; then
            mv yt-dlp-gui.exe yt-dlp-gui-${{ matrix.rid }}${SC_SUFFIX}.exe
          else
            mv yt-dlp-gui yt-dlp-gui-${{ matrix.rid }}${SC_SUFFIX}
            chmod +x yt-dlp-gui-${{ matrix.rid }}${SC_SUFFIX}
          fi

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: publish/yt-dlp-gui-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
